/* Generated By:JavaCC: Do not edit this line. RusskiyCompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RusskiyCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int PRINT = 14;
  /** RegularExpression Id. */
  int INPUT = 15;
  /** RegularExpression Id. */
  int IDENTIFIER = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int MULT = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int POW = 22;
  /** RegularExpression Id. */
  int DIVINT = 23;
  /** RegularExpression Id. */
  int MOD = 24;
  /** RegularExpression Id. */
  int LPAREN = 25;
  /** RegularExpression Id. */
  int RPAREN = 26;
  /** RegularExpression Id. */
  int SEMICOLON = 27;
  /** RegularExpression Id. */
  int LBRACE = 28;
  /** RegularExpression Id. */
  int RBRACE = 29;
  /** RegularExpression Id. */
  int ASSIGN = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"pusto\"",
    "\"tseloye\"",
    "\"drobnoye\"",
    "\"slova\"",
    "\"yesli\"",
    "\"inache\"",
    "\"kazhday\"",
    "\"poka\"",
    "\"vyvod\"",
    "\"vvod\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"//\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"0\"",
    "\"1\"",
    "\"2\"",
    "\"3\"",
    "\"4\"",
    "\"5\"",
    "\"6\"",
    "\"7\"",
    "\"8\"",
    "\"9\"",
    "\"++\"",
    "\"--\"",
  };

}
