/* RusskiyCompiler.java */
/* Generated By:JavaCC: Do not edit this line. RusskiyCompiler.java */
import java.io.*;

public class RusskiyCompiler implements RusskiyCompilerConstants {
    public static void main(String args[]) throws ParseException {
      RusskiyCompiler parser = new RusskiyCompiler(System.in);
      while (true) {
        System.out.println("------------------------------------------------");
        System.out.println("Nachalo - Compilador Russo (Digite ou CTRL+C para sair):");
        System.out.print("> ");
        try {
            parser.Programa();
            System.out.println("Codigo aceito!");
        } catch (ParseException e) {
            System.out.println("Erro sintatico: " + e.getMessage());
            parser.ReInit(System.in);
        } catch (TokenMgrError e) {
            System.out.println("Erro lexico: " + e.getMessage());
            parser.ReInit(System.in);
        }
      }
    }

  void error_skipto(int kind) throws ParseException {ParseException e = generateParseException();
  System.out.println(e.getMessage());
  Token t;
  do {
    t = getNextToken();
  } while (t.kind != kind && t.kind != EOF);
  }

// =============================
// Gramática
// =============================
  final public 
No Programa() throws ParseException {No raiz = new No("PROGRAMA"); No filho;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VOID:
      case INT:
      case FLOAT:
      case STRING:
      case IF:
      case WHILE:
      case PRINT:
      case INPUT:
      case LPAREN:
      case IDENTIFIER:
      case NUMBER:
      case STRING_LITERAL:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      filho = Comando();
if (filho != null) raiz.addFilho(filho);
    }
    jj_consume_token(0);
System.out.println("\n=== ARVORE SINTATICA ===\n");
        raiz.imprimirRaiz();
        {if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
}

  final public No Comando() throws ParseException {No n = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IF:{
      n = Condicional();
      break;
      }
    case WHILE:{
      n = Iteracao();
      break;
      }
    case PRINT:
    case INPUT:{
      n = IO();
      break;
      }
    case VOID:
    case INT:
    case FLOAT:
    case STRING:{
      n = Declaracao();
      break;
      }
    case LPAREN:
    case IDENTIFIER:
    case NUMBER:
    case STRING_LITERAL:{
      n = FraseFinalizada();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

  final public No IO() throws ParseException {No n = new No("IO"); No expr; Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PRINT:{
      jj_consume_token(PRINT);
      jj_consume_token(LPAREN);
      expr = Expressao();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
n.addFilho(new No("Comando", "vyvod")); n.addFilho(expr); {if ("" != null) return n;}
      break;
      }
    case INPUT:{
      jj_consume_token(INPUT);
      jj_consume_token(LPAREN);
      t = jj_consume_token(IDENTIFIER);
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
n.addFilho(new No("Comando", "vvod")); n.addFilho(new No("Var", t.image)); {if ("" != null) return n;}
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public No FraseFinalizada() throws ParseException {No n = null;
    try {
      n = Frase();
      jj_consume_token(SEMICOLON);
{if ("" != null) return n;}
    } catch (ParseException e) {
error_skipto(SEMICOLON);
        {if ("" != null) return new No("[ERRO DE SINTAXE]");}
    }
    throw new Error("Missing return statement in function");
}

  final public No Frase() throws ParseException {No expr; No n = new No("Frase"); No atrib;
    expr = Expressao();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INC:
    case DEC:
    case ASSIGN:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASSIGN:{
        jj_consume_token(ASSIGN);
        atrib = Expressao();
n = new No("Atribuicao"); n.addFilho(expr); n.addFilho(new No("Operador", "=")); n.addFilho(atrib); {if ("" != null) return n;}
        break;
        }
      case INC:{
        jj_consume_token(INC);
n = new No("Incremento"); n.addFilho(expr); {if ("" != null) return n;}
        break;
        }
      case DEC:{
        jj_consume_token(DEC);
n = new No("Decremento"); n.addFilho(expr); {if ("" != null) return n;}
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
{if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
}

  final public No Declaracao() throws ParseException {No n = new No("Declaracao"); No tipo; Token t; No inic = null;
    tipo = TipoEspecificador();
    t = jj_consume_token(IDENTIFIER);
    inic = OpcionalInicializacao();
    jj_consume_token(SEMICOLON);
n.addFilho(tipo); n.addFilho(new No("Var", t.image));
        if (inic != null) { n.addFilho(new No("Inicializacao")); n.addFilho(inic); }
        {if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

  final public No OpcionalInicializacao() throws ParseException {No expr = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      expr = Expressao();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
{if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
}

  final public No TipoEspecificador() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VOID:{
      t = jj_consume_token(VOID);
      break;
      }
    case INT:{
      t = jj_consume_token(INT);
      break;
      }
    case FLOAT:{
      t = jj_consume_token(FLOAT);
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return new No("Tipo", t.image);}
    throw new Error("Missing return statement in function");
}

  final public No Condicional() throws ParseException {No n = new No("IF"); No cond; No cmd; No blocoIf = new No("Bloco True"); No blocoElse = null;
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    cond = Expressao();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
n.addFilho(cond);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VOID:
      case INT:
      case FLOAT:
      case STRING:
      case IF:
      case WHILE:
      case PRINT:
      case INPUT:
      case LPAREN:
      case IDENTIFIER:
      case NUMBER:
      case STRING_LITERAL:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      cmd = Comando();
blocoIf.addFilho(cmd);
    }
    jj_consume_token(RBRACE);
n.addFilho(blocoIf);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      jj_consume_token(LBRACE);
blocoElse = new No("Bloco Else");
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VOID:
        case INT:
        case FLOAT:
        case STRING:
        case IF:
        case WHILE:
        case PRINT:
        case INPUT:
        case LPAREN:
        case IDENTIFIER:
        case NUMBER:
        case STRING_LITERAL:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        cmd = Comando();
blocoElse.addFilho(cmd);
      }
      jj_consume_token(RBRACE);
n.addFilho(blocoElse);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

  final public No Iteracao() throws ParseException {No n = new No("WHILE"); No cond; No cmd; No bloco = new No("Bloco Loop");
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    cond = Expressao();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
n.addFilho(cond);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VOID:
      case INT:
      case FLOAT:
      case STRING:
      case IF:
      case WHILE:
      case PRINT:
      case INPUT:
      case LPAREN:
      case IDENTIFIER:
      case NUMBER:
      case STRING_LITERAL:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
      cmd = Comando();
bloco.addFilho(cmd);
    }
    jj_consume_token(RBRACE);
n.addFilho(bloco); {if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

  final public No Expressao() throws ParseException {No n;
    n = ExpressaoRelacional();
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

  final public No ExpressaoRelacional() throws ParseException {No atual, prox; Token op;
    atual = ExpressaoAditiva();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:
      case NEQ:
      case LE:
      case GE:
      case GT:
      case LT:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:{
        op = jj_consume_token(EQ);
        break;
        }
      case NEQ:{
        op = jj_consume_token(NEQ);
        break;
        }
      case GT:{
        op = jj_consume_token(GT);
        break;
        }
      case LT:{
        op = jj_consume_token(LT);
        break;
        }
      case GE:{
        op = jj_consume_token(GE);
        break;
        }
      case LE:{
        op = jj_consume_token(LE);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      prox = ExpressaoAditiva();
No novoPai = new No("Op.Relacional", op.image); novoPai.addFilho(atual); novoPai.addFilho(prox); atual = novoPai;
    }
{if ("" != null) return atual;}
    throw new Error("Missing return statement in function");
}

  final public No ExpressaoAditiva() throws ParseException {No atual, prox; Token op;
    atual = ExpressaoMultiplicativa();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        op = jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        op = jj_consume_token(MINUS);
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      prox = ExpressaoMultiplicativa();
No novoPai = new No("Op.Aditivo", op.image); novoPai.addFilho(atual); novoPai.addFilho(prox); atual = novoPai;
    }
{if ("" != null) return atual;}
    throw new Error("Missing return statement in function");
}

  final public No ExpressaoMultiplicativa() throws ParseException {No atual, prox; Token op;
    atual = Termo();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POW:
      case DIVINT:
      case MULT:
      case DIV:
      case MOD:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:{
        op = jj_consume_token(MULT);
        break;
        }
      case DIV:{
        op = jj_consume_token(DIV);
        break;
        }
      case DIVINT:{
        op = jj_consume_token(DIVINT);
        break;
        }
      case MOD:{
        op = jj_consume_token(MOD);
        break;
        }
      case POW:{
        op = jj_consume_token(POW);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      prox = Termo();
No novoPai = new No("Op.Multiplicativo", op.image); novoPai.addFilho(atual); novoPai.addFilho(prox); atual = novoPai;
    }
{if ("" != null) return atual;}
    throw new Error("Missing return statement in function");
}

  final public No Termo() throws ParseException {Token t; No n;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      t = jj_consume_token(IDENTIFIER);
{if ("" != null) return new No("Var", t.image);}
      break;
      }
    case NUMBER:{
      t = jj_consume_token(NUMBER);
{if ("" != null) return new No("Num", t.image);}
      break;
      }
    case STRING_LITERAL:{
      t = jj_consume_token(STRING_LITERAL);
{if ("" != null) return new No("String", t.image);}
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      n = Expressao();
      jj_consume_token(RPAREN);
{if ("" != null) return n;}
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  /** Generated Token Manager. */
  public RusskiyCompilerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[18];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x73e00,0x73e00,0x60000,0x9800000,0x9800000,0x8000000,0x1e00,0x73e00,0x73e00,0x4000,0x73e00,0x30780000,0x30780000,0xc0000000,0xc0000000,0x6000000,0x6000000,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x1c08,0x1c08,0x0,0x0,0x0,0x0,0x0,0x1c08,0x1c08,0x0,0x1c08,0x0,0x0,0x0,0x0,0x7,0x7,0x1c08,};
	}

  /** Constructor with InputStream. */
  public RusskiyCompiler(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public RusskiyCompiler(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new RusskiyCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public RusskiyCompiler(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new RusskiyCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new RusskiyCompilerTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public RusskiyCompiler(RusskiyCompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(RusskiyCompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 18; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[45];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 18; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 45; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
